### PR TITLE
Fix typos and some broken links, remove trailing whitespace

### PR DESCRIPTION
**Pull request by mark-gerarts**
Hi! First off, thanks for your work! It's refreshing to see a well thought-out ORM these days. This PR fixes some typo's in the documentation. 

While creating the commit I also noticed there was quite a lot of trailing whitespace. I took the liberty of removing those as well. Unfortunately, this causes the commit to be quite large, so I apologize in advance for that.

### CODE REVIEW

**Comment by wolfy-j** [comment]
Thank you so much! I have to rely on grammarly since English is my second language but this app is not very reliable.

**Comment by wolfy-j** [comment]
There is known typo in m-t-m relation with “though”, I’m planning to release patch which addresses it tomorrow.

**Comment by mark-gerarts** [comment]
I'm currently reading to the docs and fixing typos when I see them, see another PR will probably be incoming in the following days :)

**Comment by wolfy-j** [comment]
Thank you! I'm will respond to any question regarding confusing parts, if there are any.

**Pull request merged**
